import React from 'react'
import Script from 'next/script'

const Contect = () => {
    return (
        <div>

            <Script>
            {`alert("CONTECT PAGE")`}
            </Script>

            Contect
        </div>
    )
}

export default Contect

export const metadata = {
    title: "contect",
    description: "Generated by create about",
};