import Image from "next/image";

export default function Home() {
  return (
    <div className=" size-80 bg-red-200">
      i am home
      <Image width={800} height={700} src="https://gratisography.com/wp-content/uploads/2024/01/gratisography-cyber-kitty-800x525.jpg" alt="billi" />
    </div>
  );
}

export const metadata = {
  title: "home",
  description: "Generated by create about",
};
